-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.0.396.4
-- Module  Version: 5.7
-- Thu Jul 16 19:23:34 2020

-- parameterized module component declaration
component mc_pll
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : mc_pll
    port map (CLKI=>__, CLKOP=>__, LOCK=>__);
